[options]
girs_dir = "gir-files"
library = "GdkPixbuf"
version = "2.0"
min_cfg_version = "2.26"
target_path = "."
work_mode = "normal"

generate = [
    "GdkPixbuf.Colorspace",
    "GdkPixbuf.InterpType",
    "GdkPixbuf.PixbufAlphaMode",
    "GdkPixbuf.PixbufError",
    "GdkPixbuf.PixbufLoader",
    "GdkPixbuf.PixbufSimpleAnim",
]

manual = [
    "GdkPixbuf.Pixbuf",
    "GdkPixbuf.PixbufAnimation",
    "GdkPixbuf.PixbufAnimationIter",
    "GdkPixbuf.PixbufFormat",
    "GLib.Bytes",
    "GLib.Error",
]
